// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://isvdaakowydrqlenrvnp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlzdmRhYWtvd3lkcnFsZW5ydm5wIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5NzA4MzgsImV4cCI6MjA2NTU0NjgzOH0.mhtQ1-nPziiF0OZ2gBzqehGHk-F6zGSwRxk9uS5rfeA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);